apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "org.fullname" . }}
  labels:
    app: {{ include "org.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "org.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "org.name" . }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "org.name" . }}
          image: "{{ .Values.global.image.repository }}:organization-{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.SPRING_DATASOURCE_URL | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SPRING_DATASOURCE_USERNAME_SECRET.name }}
                  key: {{ .Values.env.SPRING_DATASOURCE_USERNAME_SECRET.key }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SPRING_DATASOURCE_PASSWORD_SECRET.name }}
                  key: {{ .Values.env.SPRING_DATASOURCE_PASSWORD_SECRET.key }}

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3 