apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chat.fullname" . }}
  labels:
    app: {{ include "chat.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chat.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "chat.name" . }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "chat.name" . }}
          image: "{{ .Values.global.image.repository }}:chatbot-{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}