services:
 
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: organization
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vikash@123#
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  organization-service:
    build: ./organization-service
    container_name: organization-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/organization
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Vikash@123#
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
 
  chatbot-service:
    build: ./chatbot-service
    container_name: chatbot-service
    ports:
      - "8084:8084"
 
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - organization-service
      - chatbot-service
 
volumes:
  postgres_data:
 