apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  labels:
    app: api-gateway
data:
  application.properties: |
    spring.application.name=gateway-service
    server.port=8080

    # ================= ORGANIZATION SERVICE =================
    spring.cloud.gateway.routes[0].id=organization-service
    spring.cloud.gateway.routes[0].predicates[0]=Path=/org/**
    spring.cloud.gateway.routes[0].filters[0]=RewritePath=/org/(?<segment>.*), /${segment}
    spring.cloud.gateway.routes[0].uri=http://organization-service:8082

    # ================= CHATBOT SERVICE =================
    spring.cloud.gateway.routes[1].id=chatbot-service
    spring.cloud.gateway.routes[1].predicates[0]=Path=/chat/**
    spring.cloud.gateway.routes[1].filters[0]=RewritePath=/chat/?(?<segment>.*), /api/chat
    spring.cloud.gateway.routes[1].uri=http://chatbot-service:8084