apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: girishhardia/chatbot:gateway-latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: JWT_SECRET

          volumeMounts:
            - name: gateway-config
              mountPath: /config/application.properties
              subPath: application.properties

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: gateway-config
          configMap:
            name: gateway-config