# stage 1 : maven image pull and building the application
FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

#stage 2 - running application
FROM eclipse-temurin:21

WORKDIR /app

COPY --from=builder /app/target/chatbot-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8084

ENTRYPOINT ["java","-jar","app.jar"]