global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'chatbot-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['chatbot-service:8084']

  - job_name: 'organization-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['organization-service:8082']