# -------STAGE 1 : BUILD -------
FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

#Copy the pom.xml first for layer caching
COPY pom.xml .

#Copy the source code
COPY src ./src

#Build the jar
RUN mvn clean package -DskipTests

# -------STAGE 2 : RUNTIME -------
FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "app.jar"]