spring.application.name=chatbot-service


server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot_db
spring.datasource.username=postgres
spring.datasource.password=Vikash@123#

spring.sql.init.mode=always