apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gw.fullname" . }}-config
  labels:
    app: {{ include "gw.name" . }}
data:
  application.properties: |
{{ .Values.config.applicationProperties | nindent 4 }}