{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gw.fullname" . }}-secret
  labels:
    app: {{ include "gw.name" . }}
type: Opaque
stringData:
{{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}