spring.application.name=organization-service


server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/organization
spring.datasource.username=postgres
spring.datasource.password=Vikash@123#
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#"Hey, whenever the application starts,
#run schema.sql (and data.sql) automatically"
spring.sql.init.mode=always