global:
  image:
    repository: girishhardia/chatbot
    pullPolicy: IfNotPresent

  imagePullSecrets:
    - name: dockerhub-secret

# Subchart overrides (parent overrides child chart values)
organization-service:
  replicaCount: 1
  image:
    tag: "0.0.0"   # CI will override: organization-<BUILD>-<GITSHA>
  service:
    type: ClusterIP
    port: 8082

  
  env:
      - name: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://chatbot-platform-postgresql:5432/organizationdb"

      - name: SPRING_DATASOURCE_USERNAME
        value: "orguser"

      - name: SPRING_DATASOURCE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: chatbot-platform-postgresql
            key: password



chatbot-service:
  replicaCount: 1
  image:
    tag: "0.0.0"   # CI will override: chatbot-<BUILD>-<GITSHA>
  service:
    type: ClusterIP
    port: 8084
  env:
      - name: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://chatbot-platform-postgresql:5432/organizationdb"

      - name: SPRING_DATASOURCE_USERNAME
        value: "orguser"

      - name: SPRING_DATASOURCE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: chatbot-platform-postgresql
            key: password

      - name: RABBITMQ_HOST
        value: "rabbitmq"

      - name: RABBITMQ_PORT
        value: "5672"

      - name: RABBITMQ_USERNAME
        value: "admin"

      - name: RABBITMQ_PASSWORD
        value: "admin"

      - name: OPENAI_API_KEY
        value: "your_openai_api_key"

      - name: OPENAI_MODEL
        value: "gpt-4"

      - name: OPENAI_URL
        value: "https://api.openai.com/v1/chat/completions" 

api-gateway:
  replicaCount: 1
  image:
    tag: "0.0.0"   # CI will override: gateway-<BUILD>-<GITSHA>
  service:
    type: NodePort
    port: 8080
    nodePort: 30080
  secret:
    enabled: true
  env:
      - name: ORG_SERVICE_URL
        value: "http://chatbot-platform-organization-service:8082"

      - name: CHAT_SERVICE_URL
        value: "http://chatbot-platform-chatbot-service:8084"

rabbitmq:
  
  image:
    registry: docker.io
    repository: bitnamilegacy/rabbitmq   # ✅ IMPORTANT FIX
    tag: "4.1.3-debian-12-r1"            # ✅ valid existing tag
 
  auth:
    username: admin
    password: admin
  
  replicaCount: 1
  
  persistence:
    enabled: true
    size: 1Gi

  
  livenessProbe:
    enabled: true
    initialDelaySeconds: 240
    periodSeconds: 30
    timeoutSeconds: 20
    failureThreshold: 10

  readinessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 20
    failureThreshold: 15

  extraPlugins: "rabbitmq_management"


postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "latest"

  auth:
    database: organizationdb
    username: orguser
    password: orgpassword

  primary:
    persistence:
      enabled: true
      size: 1Gi

kube-prometheus-stack:
  grafana:
    adminPassword: admin

    service:
      type: NodePort
      nodePort: 30090

  prometheus:
    service:
      type: NodePort
      nodePort: 30091