global:
  image:
    repository: girishhardia/chatbot
    pullPolicy: IfNotPresent

  imagePullSecrets:
    - name: dockerhub-secret

# Subchart overrides (parent overrides child chart values)
organization-service:
  replicaCount: 1
  image:
    tag: "0.0.0"   # CI will override: organization-<BUILD>-<GITSHA>
  service:
    type: ClusterIP
    port: 8082

  env:
    - name: SPRING_DATASOURCE_URL
      value: "jdbc:postgresql://chatbot-platform-postgresql:5432/organizationdb"
    - name: SPRING_DATASOURCE_USERNAME
      value: "orguser"
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: chatbot-platform-postgresql
          key: password


chatbot-service:
  replicaCount: 1
  image:
    tag: "0.0.0"   # CI will override: chatbot-<BUILD>-<GITSHA>
  service:
    type: ClusterIP
    port: 8084

api-gateway:
  replicaCount: 1
  image:
    tag: "0.0.0"   # CI will override: gateway-<BUILD>-<GITSHA>
  service:
    type: NodePort
    port: 8080
    nodePort: 30080
  secret:
    enabled: true

postgresql:
  auth:
    database: organizationdb
    username: orguser
    password: orgpassword

  primary:
    persistence:
      enabled: true
      size: 1Gi

kube-prometheus-stack:
  grafana:
    adminPassword: admin

    service:
      type: NodePort
      nodePort: 30090

  prometheus:
    service:
      type: NodePort
      nodePort: 30091